apiVersion: 1

datasources:
  - name: PostgreSQL Warehouse
    type: postgres
    url: postgres-warehouse:5432
    database: warehouse
    user: warehouse
    secureJsonData:
      password: warehouse
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
